### ISSUE TITLE
AI Behavior: AI Stops Moving

### ISSUE THREAD

**Issue by James-Gryphon** [grassblade-entertainment/greebles-issues#11] opened 2023-02-27 22:03 UTC
Sometimes the player AI stops moving. Occasionally, it can even be frozen and inert for multiple levels, or the rest of the game. This is buggy and incorrect behavior; the classical AI is almost always in motion (with the exception of when moving would result in immediate death).

**Comment by drautb** [comment] 2023-08-17 12:05
The root cause for this one is the same as https://github.com/grassblade-entertainment/greebles-issues/issues/13 - the same data corruption made the AI think that it had no open movement paths available.

**Comment by drautb** [comment] 2023-08-22 17:52
Released in 0.4.1.

**Closed as completed by drautb** 2023-08-22 17:52 UTC
Labels: pending release
