### ISSUE TITLE
Occasionally Unable to Push in Specific Direction

### ISSUE THREAD

**Issue by gratednutmeg** [grassblade-entertainment/greebles-issues#44] opened 2023-03-25 19:05 UTC
Platform: MacOS (Mac M1, Ventura 13.1)
Keyboard setup is attached.

Every so often, I'll be unable to push (space bar) in a specific direction, so far I (think) only up. I can still turn my player up, and can still push blocks in other directions. This seems to occur after I've pressed a few buttons at the same time/possibly died while pressing a button?, but I haven't been able to find consistent steps to reproduce since I don't notice it until I try pushing in that direction shortly after. Once it happens, I won't be able to push in that direction on the next level either, but *will* be able to push other directions. I've been playing with one human, other players disabled, and it's happened on a few different levels within the first ten. It resolves after I quit and reopen OR use the 'kill game' option. I realize that's a vague set of steps to reproduce, but I'm trying to keep an eye out for what sequence actually causes it and will update this ticket with a comment if I can figure out specifics. Thank you for porting this!

<img width="802" alt="image" src="https://user-images.githubusercontent.com/28812263/227736406-52d05c9b-50e5-4b07-af68-da4df144a33b.png">

**Comment by drautb** [comment] 2023-03-26 01:09
Thanks for the report - probable duplicate of #13.

**Comment by drautb** [comment] 2023-08-12 04:39
Should be fixed in 0.4.0, but please re-open if you see it again.

**Closed as completed by drautb** 2023-08-12 04:39 UTC
Labels: gamebreaker, duplicate, pending release
